# Generated by Django 4.2.1 on 2023-06-12 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petsapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=100)),
                ('student_age', models.IntegerField()),
                ('student_email', models.EmailField(max_length=254)),
                ('student_location', models.CharField(max_length=50)),
                ('student_course', models.CharField(max_length=100)),
            ],
        ),
    ]
