# Generated by Django 4.2.1 on 2023-06-20 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petsapp', '0004_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='pets',
            name='animal_type',
            field=models.CharField(choices=[('D', 'Dog'), ('c', 'Cat')], default='NA', max_length=30),
        ),
        migrations.AddField(
            model_name='pets',
            name='price',
            field=models.FloatField(default=0),
        ),
    ]
