# Generated by Django 4.2.1 on 2023-07-10 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petsapp', '0005_pets_animal_type_pets_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pets',
            name='age',
            field=models.IntegerField(),
        ),
    ]
